#!/usr/bin/env php
<?php

$pmd = simplexml_load_file("/Users/dalkire/scripts/phpmd.pi_hull.xml");
$violations = array();

foreach ($pmd->file as $file) {
  $violations[] = array(
    'file' => (string) $file['name'][0],
    'rule' => (string) $file->violation['rule'],
    'violation' => (string) $file->violation
  );
}

echo json_encode($violations);
exit;
foreach ($violations as $violation) {
  echo "=============================\n\n\n";
  print_r($violation);
}